language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - python setup.py coverage_pep8_test
after_script:
  # https://github.com/codeclimate/python-test-reporter
  - codeclimate-test-reporter